version: "3.0"
services:
  api:
    image: jeffrygonzalez/todos-api:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    links:
      - mongo

